### ISSUE TITLE
Preprocessing used

### ISSUE THREAD

**Issue by surajmahangade** [facebookresearch/TimeSformer#10]
https://github.com/facebookresearch/TimeSformer/blob/2a181ec59c58066ffad20bd3ee876e6ca3bf90b4/lib/datasets/loader.py#L102
In this line, I see the loaders are not using any transform. I don't know if I am looking at the right location. Wanted to know the exact preprocessing so that I could use it for testing in some other script.

Thank you

**Comment by surajmahangade** [comment]
I got it, Can I know what is the mean and std value used to normalize the frames for the HowTo100M and K400 dataset.
Or how it is calculated. That would be very helpful.

Thank you

**Comment by gberta** [comment]
These are the mean and std values used for data normalization: _C.DATA.MEAN = [0.45, 0.45, 0.45], _C.DATA.STD = [0.225, 0.225, 0.225].

**Comment by surajmahangade** [comment]
Thank you!!
