### ISSUE TITLE
Loading a pretrained model minimally

### ISSUE THREAD

**Issue by tcapelle** [facebookresearch/TimeSformer#11]
Would you mind putting simple notebook on how to load a pretrained model minimally?
Something like:
```python
import torch
from lib import TimeSformer
simple_config = blablabla

model = TimeSformer(
simple_config,
)

video = torch.randn(2, 8, 3, 224, 224) # (batch x frames x channels x height x width)

pred = model(video,) # (2, 10)
```
so one can use the model elsewhere?
I am having a hard time understanding all the file parsing.

**Comment by gberta** [comment]
I updated the code. you can now do this as follows:

```python
import torch
from lib.models.vit import TimeSformer

model = TimeSformer(img_size=224, num_classes=400, num_frames=8, attention_type='divided_space_time',  pretrained_model='/path/to/pretrained/model.pyth')

dummy_video = torch.randn(2, 3, 8, 224, 224) # (batch x channels x frames x height x width)

pred = model(dummy_video,) # (2, 400)
```

Hope this helps!

**Comment by tcapelle** [comment]
This really helps!I put a small tutorial here on how to train a Timesformer using fastai if you are interested:
https://github.com/fastai/fastai/blob/master/nbs/24_tutorial.image_sequence.ipynb

**Comment by tcapelle** [comment]
Where I can get the model file?

**Comment by gberta** [comment]
You can find the links to our pretrained models under Model Zoo section in the front page of this repo (https://github.com/facebookresearch/TimeSformer).

**Comment by tcapelle** [comment]
yeah, my bad, that's why I removed the question. Thanks again!
