### ISSUE TITLE
Dataloader Problem

### ISSUE THREAD

**Issue by easquelcannotcode** [facebookresearch/TimeSformer#12]
Thanks for your code. Could you please show me the *.csv* file sample？
When I tried to load videos, there is always a bug indicating that 
```
Failed to meta load video idx 24899 from YvYW5eWaNKE; trial 0
Failed to meta load video idx 24899 from YvYW5eWaNKE; trial 1
Failed to meta load video idx 148797 from 5vPDEg8cefE; trial 0
......
```

**Comment by gberta** [comment]
The lists are available at: https://www.dropbox.com/personal/research/21W_TimeSformer_code_release/Kinetics_lists. You have to make sure that the videos on the lists are present, and that they are also not faulty, if you want to avoid this message.

**Comment by easquelcannotcode** [comment]
Sorry, but I can't open your website. It indicates the file is gone. Afterwards, I used my own data and data list instead. The data list is at https://drive.google.com/drive/folders/1Z3DHYO-GTaZUHiEELXUL6fPeSWQeaVpU?usp=sharing.  But there are still the wrong errors like
```
Failed to meta load video idx 25713 from canoeing_or_kayaking/0gkK9tmWG-k; trial 0
......
```
I checked the video of 0gkK9tmWG-k.mp4 on my server, it is present and not faulty. The video path is 
```
/data/Kinetics/train/canoeing_or_kayaking/0gkK9tmWG-k.mp4
```
I don't know if there is anything wrong.

**Comment by easquelcannotcode** [comment]
Thanks for your answer. I already fixed this bug!!

**Comment by gberta** [comment]
If you could describe how you fixed this issue that would be great. It might be useful for others as well. Thank you!

**Comment by easquelcannotcode** [comment]
I put all of the absolute video paths in the *self._path_to_videos* list, including the suffix of the file name like *.mp4*. And then it works.
