### ISSUE TITLE
Error while decoding MB xx, byte stream xx

### ISSUE THREAD

**Issue by easquelcannotcode** [facebookresearch/TimeSformer#13]
Thanks for your code! When I tried to use my own K400 data for training, I came across this problem as follows.
```
error while decoding MB 6 6, bytestream 224
gray chroma
error while decoding MB 9 2, bytestream 3802
Reference 3 >= 3
error while decoding MB 7 6, bytestream 402
Reference 2 >= 2
error while decoding MB 12 5, bytestream 119
error while decoding MB 15 9, bytestream -43
gray chroma
left block unavailable for requested intra4x4 mode -1
error while decoding MB 0 4, bytestream 1011
Reference 4 >= 4
......
```
However, the training process do not exit but goes well. This problem notification sometimes shows on the terminal interface every several iterations. Do you know the reason?

**Comment by gberta** [comment]
I haven't seen these types of errors in my runs. It might have something to do either with the videos on your disk (maybe some of them are corrupted?) or the ffmpeg version (less likely in my opinion).
