### ISSUE TITLE
Question about gflops?

### ISSUE THREAD

**Issue by XUSean0118** [facebookresearch/TimeSformer#17]
The complexity of TimeSformer is reported as **13** gflops in the paper, but the model in this repo is **189.878** gflops.

Is there any different setting between paper model and repo model?

I calculate the gflops via https://github.com/Lyken17/pytorch-OpCounter.

```python
import torch
from timesformer.models.vit import TimeSformer

from thop import profile, clever_format

model = TimeSformer(img_size=224, num_classes=400, num_frames=8, attention_type='divided_space_time')

dummy_video = torch.randn(1, 3, 8, 224, 224) # (batch x channels x frames x height x width)

macs, params = profile(model, inputs=(dummy_video,))
macs, params = clever_format([macs, params], "%.3f")
print(f'Computational complexity: {macs}')
print(f'Number of parameters: {params}')
```

**Comment by gberta** [comment]
Your calculations are correct. The first version of the paper had an incorrect number of GFLOPs. Please check out our latest draft on arxiv (https://arxiv.org/pdf/2102.05095.pdf) for the correct computational cost numbers. It also has some additional experiments with respect to the first version.
