### ISSUE TITLE
The data class order

### ISSUE THREAD

**Issue by xvjiarui** [facebookresearch/TimeSformer#2]
Thanks for releasing the code. 

Could please you also provide the `*.csv` files for each dataset? Since if the order of the class is different, directly inferencing from provided checkpoint may yield incorrect prediction results. 

Thanks in advance.

**Comment by gberta** [comment]
The class order is the same as defined in the original Kinetics dataset. However, for your convenience I have uploaded the csv files for Kinetics-400, and Kinetics-600 datasets. You can find them in this link: https://www.dropbox.com/sh/hrzplvsh1tklrfr/AABXMk1Ml9c0nk5qseViKUZAa?dl=0.
