### ISSUE TITLE
About k400 preparation

### ISSUE THREAD

**Issue by wenyuqing** [facebookresearch/TimeSformer#21]
Thanks for your code! But I meet some problem loading K400 dataset.
Could you please provide your train.csv, val.csv, test.csv files in the format of : ?
path_to_video_1 label_1
path_to_video_2 label_2
 Also , could you tell me the fomat and the path of the video? 
Is it saved in a format like this?
/train/abseiling/-3B32lodo2M_000059_000069/RGB_frames.zip
or /train/-3B32lodo2M_000059_000069.mp4?

**Comment by IvanLLL** [comment]
The latter format (```/path/to/xxx.mp4```) works for me.

**Comment by wenyuqing** [comment]
> The latter format (`/path/to/xxx.mp4`) works for me.

Thanks! I have one more question about the size of the video, why do we need to resize the video to the short edge size of 256 manually before training? How to resize it ?

**Comment by gberta** [comment]
It's just a standard way of pre-processing kinetics. You don't have to do it, but it was shown in previous papers that it leads to empirically better results.

**Comment by L666888999** [comment]
> 感谢您的代码！但是我在加载 K400 数据集时遇到了一些问题。您能否以以下格式提供您的火车.csv、价值.csv、测试.csv文件： ？ path_to_video_1 label_1 path_to_video_2 label_2 另外，你能告诉我视频的 fomat 和路径吗？它是否以这样的格式保存？ /train/abseiling/-3B32lodo2M_000059_000069/RGB_frames.zip or /train/-3B32lodo2M_000059_000069.mp4？

您好，您这边可以提供一下预处理后的.csv文件吗？谢谢啦！
