### ISSUE TITLE
pretrained on ImageNet-1K or ImageNet-21K?

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/TimeSformer#23]
Hi, 

Thanks for your work.

From the paper `Is Space-Time Attention All You Need for Video Understanding`,  Table 2 and Table 3, I noticed that TimeSformer pretrained on **ImageNet-21K** achieves about 78.0 top-1 acc.

But from this codebase,  https://github.com/facebookresearch/TimeSformer/blob/main/timesformer/models/vit.py#L32-L37,
I thought the pretrain model is on **ImageNet-1K**.  

Please tell me if I misunderstand anything. Thanks.

**Comment by gberta** [comment]
The models provided in this codebase are pre-trained on ImageNet-21K.
