### ISSUE TITLE
 models retrained with ImageNet-1K and ImageNet-21K have very similar results

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/TimeSformer#24]
Hi,

I train the TimeSformer with ImageNet-1K and ImageNet-21K pretrained model, and the results are very close, which is different from the table 3 in the paper:
![image](https://user-images.githubusercontent.com/28682908/118353286-2a0bb980-b598-11eb-97f1-23bcd749fa79.png)

The results I got are:
|Method | Pretraining |  K400 top-1 | K400 top-5|
|--------| ------------|-------------|------------|
|TimeSformer| ImageNet-1K | 77.27 | 93.07          |
|TimeSformer | ImageNet-21K| 77.38| 93.30        |

Would you mind giving some hints about this result?

**Comment by gberta** [comment]
The checkpoint that you are referring as imagenet-1k pretraining (i.e., https://github.com/facebookresearch/TimeSformer/blob/main/timesformer/models/vit.py#L32-L37) is actually a checkpoint pretrained on imagenet-21k, and then finetuned on imagenet-1k. Therefore, the results that you are getting makes sense. At the moment, the code doesn't include checkpoints pretrained on imagenet-1k only. For those checkpoints you can refer to the Data Efficient Image Transformer codebase: https://github.com/facebookresearch/deit

**Comment by ShoufaChen** [comment]
Thanks for your reply. I see.
