### ISSUE TITLE
Could you release the codes for "Axial Attention" and "Sparse Local Global Attention"

### ISSUE THREAD

**Issue by yushuinanrong** [facebookresearch/TimeSformer#25]
Thanks for sharing the codebase for this interesting work. I'm interested to run experiments using the "Axial Attention" and "Sparse Local Global Attention" proposed in the paper, would you please share the codes for creating these two attention mechanisms?

**Comment by gberta** [comment]
I'm not planning to release it at the moment. However, these should be pretty straightforward to implement using einops.

**Comment by nikhilCad** [comment]
@yushuinanrong did you write it?
