### ISSUE TITLE
How to get Flops and number of parameters?

### ISSUE THREAD

**Issue by kkjh0723** [facebookresearch/TimeSformer#26]
Thanks for sharing the code.
I saw Flops and parameter information in the paper.
How can I get Flops and number of parameters of the model in the code?

**Comment by gberta** [comment]
I used fvcore package for that (you might need to modify their code a bit though). When you can simply set the LOG_MODEL_INFO flag to True, and it will output FLOPS and the number of parameters.

**Comment by kkjh0723** [comment]
Thanks @gberta , I could get FLOPS and parameters with LOG_MODEL_INFO flag.
