### ISSUE TITLE
How to pretrain on ImageNet?

### ISSUE THREAD

**Issue by wenyuqing** [facebookresearch/TimeSformer#27]
Thanks for your code and reply!
I notice that the code does not involve pretraining on ImageNet. Could you please provide the pretrained weights on ImageNet 1K and ImageNet21K? Thanks !

**Comment by gberta** [comment]
The provided code already uses ImageNet-21K pretrained models, so you don't need to do anything for that. For ImageNet-1K pretraining, you should check out Data Efficient Image Transformer (DeiT) codebase, and use their provided checkpoints for initialization.

**Comment by wenyuqing** [comment]
Thanks a lot, I'll check it.
