### ISSUE TITLE
FC layer in temporal branch

### ISSUE THREAD

**Issue by wenyuqing** [facebookresearch/TimeSformer#29]
https://github.com/facebookresearch/TimeSformer/blob/a68150a495174714480e6a4d2935d833d24aad62/timesformer/models/vit.py#L129

Hi, I noticed that there's a FC layer after temporal attention, could you please tell me why do you design this layer?

**Comment by gberta** [comment]
The temporal_fc layer is not designed to increase the capacity of the model. It's meant to ensure that the temporal features are learned gradually without destroying the spatial features that the model is initialized with.

Specifically, the temporal_fc layer is first initialized with zero weights, so during the first training iterations, the model only utilizes spatial information. As the training progresses, the model then learns to gradually incorporate temporal information. Our experiments suggest that this is an effective way to train TimeSformer.

**Comment by wenyuqing** [comment]
Thank you very much for your reply! I understand it now.
