### ISSUE TITLE
ImageNet Weights by Default?

### ISSUE THREAD

**Issue by RaivoKoot** [facebookresearch/TimeSformer#30]
If I do 
```python
model = TimeSformer(img_size=224, num_classes=400, num_frames=8, attention_type='divided_space_time')
```
Does the model get initialized with ImageNet ViT weights or does it get initialized with pretrained weights from a video dataset?

**Comment by gberta** [comment]
If you provide a path to a pretrained model as one of the flags, it will load that model. Otherwise, it will load a pretrained ImageNet model.
