### ISSUE TITLE
Where should I add ROI layer?

### ISSUE THREAD

**Issue by AllenAIVision** [facebookresearch/TimeSformer#34]
Excuse me, I want to train timesformers on Ava. It seems that the ROI layer can only be placed before attention blocks. In this way, attention blocks will be calculated N times, where N is the number of bboxes. That will make timesformers slowly?  Thank you!

**Comment by gberta** [comment]
We haven't run any experiments on AVA. Therefore, you might need to experiment with different design choices in this case.
