### ISSUE TITLE
out of memory 

### ISSUE THREAD

**Issue by NehalD99** [facebookresearch/TimeSformer#38]
Hi Gedas,

Thanks for publishing the paper and code with results. I have a little memory issues running the code on a 16 GB Tesla T4 with custom video data.
For a batch size of 1, clipsize of T=8, spatial 224 X 224, I am able to run by lowering the num_heads and depth to 6 with pretrained=True to fine-tune the model for classification. 
For a clipsize of T=16,spatial 224X224 I run out of GPU memory for fine-tuning. Are there any ways I could optimize for GPU memory by making modifications in the model?
Also, do you have any pre-trained K400/600 T=16, spatial 224X224 models available?

Thank you,
Nehal

**Comment by gberta** [comment]
I would expect that for T=8, and spatial crop of 224x224, you shouldn't have any memory related issues. Are you using latest cuda/cudnn packages? 

For a clip size of T=16, there might be memory issues (even though I haven't done extensive experiments using 16GB GPUs). You could try reducing the depth/number of layers in a model then fine-tune it, and see how it performs. That's probably the first thing I would try.  

Unfortunately, I don't have  pre-trained K400/600 T=16, spatial 224X224 models. What is your goal in this case? If you want to fine-tune on a smaller downstream dataset, you can try fine-tuning from K400/600 T=8 (or even T=96) 224X224 models. I think that such a setup would still work reasonably well.

**Comment by NehalD99** [comment]
Thanks for the response. The packages are latest. The goal is to train on higher clip size 16 to get better performance compared to clip size 8. I shall try fine-tuning from higher clip-size models as you mentioned.
