### ISSUE TITLE
About implementation of Sparse Local Global attention

### ISSUE THREAD

**Issue by Gptao** [facebookresearch/TimeSformer#4]
In your paper, _For each patch (p, t), (L+G) first computes a local attention by considering the neighboring F × H/2 × W/2 patches and then calculates a sparse global attention over the entire clip using a stride of 2 patches along the temporal dimension and also the two spatial dimensions._  
I want to know how to find adjacent patches in a certain area for a patch when calculating attention. Thanks！

**Comment by gberta** [comment]
We used einops to accomplish this. In particular the implementation was inspired by this tutorial: https://github.com/arogozhnikov/einops/blob/master/docs/2-einops-for-deep-learning.ipynb. Feel free to check it out.
