### ISSUE TITLE
Visualization of space-time attention

### ISSUE THREAD

**Issue by qideng7** [facebookresearch/TimeSformer#40]
May I know which variable is visualized as the space-time attention in Figure 7 in your paper? Is it in one of attention head, the attention weights of cls_token with regarding to patches (14*14) in each frame?
![image](https://user-images.githubusercontent.com/35273269/120406840-aa544d80-c300-11eb-8ce8-8455fba42281.png)

Thank you for your help!

**Comment by gberta** [comment]
It's essentially an average attention over all heads rolled out from the output layer all the way to the input layer. We follow the attention rollout recipe from: https://arxiv.org/pdf/2005.00928.pdf. You can check it out for more details.

**Comment by qideng7** [comment]
Thank you so much! That's super helpful!
