### ISSUE TITLE
Statistics of Kinetics

### ISSUE THREAD

**Issue by irvingzhang0512** [facebookresearch/TimeSformer#41]
Hi, thanks for your work!

Could you please share the number of videos for train/val set?

~I have already download kinetics400 videos and annotations from [cvdf](https://github.com/cvdfoundation/kinetics-dataset). There are 240k training videos. However, not all of them (about 238k-239k videos) are in [train annotations](https://s3.amazonaws.com/kinetics/400/annotations/train.csv).~
A bug of my own codes

**Comment by gberta** [comment]
The Kinetics dataset that I used for my experiments had ~240K training videos, and 19.7K validation videos.

**Comment by irvingzhang0512** [comment]
Thank you
