### ISSUE TITLE
Can I train Kinetics600 with four GPUs(V100)?

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/TimeSformer#42]

**Comment by gberta** [comment]
Yes, you should be able to do it. I tried it on Kinetics-400, and while it takes much longer to do so I was able to get comparable results.

**Comment by Note-Liu** [comment]
> Yes, you should be able to do it. I tried it on Kinetics-400, and while it takes much longer to do so I was able to get comparable results.

Thank you for your reply. I'll have a try.
