### ISSUE TITLE
Question about Optimizer SGD, why? 

### ISSUE THREAD

**Issue by Joeycho** [facebookresearch/TimeSformer#55]
Hello,

In the paper, SGD was used for training although ADAM or ADAMW is also supported from SlowFast framework.

Is there any reason to choose SGD, rather than ADAM or ADAMW?

With my lack of experiments, ADAM just did not work well as SGD with TimeSformer, but maybe I should try it again.

**Comment by gberta** [comment]
I didn't have enough time to explore Adam optimizer, and other optimization related hyperparameters before the submission deadline. As you can see from our configuration files, we use a very simple and short optimization scheme. However, I suspect that TimeSformer's performance could be substantially improved by switching to Adam optimizer and also by tuning other optimization related hyperparameters.
