### ISSUE TITLE
Issue loading kinetics data

### ISSUE THREAD

**Issue by kahnchana** [facebookresearch/TimeSformer#56]
Evaluation on the test set fails with following halfway through: `RuntimeError: Failed to fetch video after 10 retries.` This comes up halfway through the test loop over the dataset. I am using the default config files and code provided for Kinetics-400. 

Also, during training, following warning comes up often: `Failed to decode video idx 13008 from ....` Is this normal?

**Comment by gberta** [comment]
This means that some of your videos are either missing or are corrupted. You can either re-download the dataset from https://github.com/cvdfoundation/kinetics-dataset, or remove the corrupted/missing files from your train/test lists.

**Comment by kahnchana** [comment]
Thanks a lot. Some videos were getting corrupt when I was downsampling. Fixing this eliminated this warning.
