### ISSUE TITLE
Regarding attention visualisation using Attention Rollout scheme.

### ISSUE THREAD

**Issue by victor-psiori** [facebookresearch/TimeSformer#57]
Hi,
Thanks for the cool work. 
The paper mentions about learned attention visualization using Attention Rollout scheme presented in **Quantifying Attention Flow in Transformers (Abnar and Zuidema, 2020)**. I wasn't able to locate the corresponding visualization class/files in repo.
Could you tell me if the repo contains the mentioned visualization related files? 
If so, could you please point to me location?

Thanks,
Victor

**Comment by gberta** [comment]
The repo doesn't contain the attention visualization code. However, there are public implementations of this visualization scheme that are easy to integrate with the existing code. That's what I did to visualize the attention masks.

**Comment by victor-psiori** [comment]
I see. Thanks a lot.

**Comment by victor-psiori** [comment]
Hi,
We were trying to reproduce the results for a similar architecture. For the attention visualization, I am currently using the implementation: [https://github.com/jacobgil/vit-explain](https://github.com/jacobgil/vit-explain). The repo also uses scheme presented in **Quantifying Attention Flow in Transformers (Abnar and Zuidema, 2020)**.
If it's not much trouble, could you please point to the public implementation you have used for generating the visualizations provided in paper?

Thanks,
Victor

**Comment by gberta** [comment]
I used the code from the following codebase: https://github.com/samiraabnar/attention_flow/blob/2272b01eb88d83eb368d841bb4e572330c592929/attention_graph_util.py#L104

**Comment by victor-psiori** [comment]
Thanks a lot.

**Comment by Holmes-Alan** [comment]
@victor-psiori hello, have you figured out how to visualize the attention map?

**Comment by victor-psiori** [comment]
@Holmes-Alan yes, I used the implementation here: [https://github.com/jacobgil/vit-explain](https://github.com/jacobgil/vit-explain)

**Comment by Holmes-Alan** [comment]
@victor-psiori This link implements on ViT visualization. It is not for TimeSformer. How do you visualize both spatial and temporal attention on the input frames?

**Comment by mohamedmansour0** [comment]
> I used the code from the following codebase: https://github.com/samiraabnar/attention_flow/blob/2272b01eb88d83eb368d841bb4e572330c592929/attention_graph_util.py#L104

@gberta can you please elaborate more how did you used that code to get the output presented in figure (7) of your paper

**Comment by YNawal** [comment]
@gberta Could you please share with us your code.

**Comment by gv237-07** [comment]
@gberta could you please share how you integrated the attention visualisation code to show attention outputs from timeSformer?

**Comment by gberta** [comment]
Apologies, I wasn't aware that this issue was still open. Unfortunately, I cannot share the visualization code since I'm not affiliated with Facebook anymore, and thus, I don't have access to my original codebase.

**Comment by gv237-07** [comment]
ok no worries. may i ask @victor-psiori if he could share his attention visualisation code please? as the one he linked is only for ViT. Thank you in advance

**Comment by victor-psiori** [comment]
Hi, unfortunately contract with my employer doesn't allow me to release the code yet. We would definitely release the code and related works once our results are final. Sorry about this.
Btw, all we did for visualization was extract the attention probabilities, reshape them to match image dimensions, superimpose them onto the images. All the best.

**Comment by leobxpan** [comment]
hi @victor-psiori, i'm wondering when you use vit-explain, for each frame, do you take the corresponding temporal channel of the output and do the attention rollout thing to multiply those attention matrices? Also, did you just multiply the spatial attention matrices? how did you treat the temporal ones? I appreciate your help.

**Comment by yiyixuxu** [comment]
I implemented the rolled attention for TimeSformer here
https://github.com/yiyixuxu/TimesFormer_rolled_attention
