### ISSUE TITLE
About Mixup

### ISSUE THREAD

**Issue by Huntersts** [facebookresearch/TimeSformer#6]
Hi，
I find there is Mixup class in the  function of 'train_epoch'. But it looks like be disabled. Did you test this trick when training the model?

**Comment by gberta** [comment]
I tried a few experiments with Mixup but didn't observe any significant differences from my current training setup. 

Having said this, I think that more thorough experiments with different data augmentation techniques might lead to further improvements. I haven't had enough time to explore this direction.

**Comment by Huntersts** [comment]
Thx.
 And I also find the max epoch is 15 for Kinetics in the released code. So, it takes 14.3 hours to train TimeSFormer for 15 epochs using 32GPUs, am i right?

**Comment by gberta** [comment]
Yes.

**Comment by Huntersts** [comment]
Thx
