### ISSUE TITLE
Run test_net.py ERROR!

### ISSUE THREAD

**Issue by wsh-nie** [facebookresearch/TimeSformer#61]
Hi! With command `python toolss/run_net.py --cfg configs/Kinetics/TimeSformer_divST_8x32_224.yaml DATA.PATH_TO_DATA_DIR dataset/kinetics400 NUM_GPUS 4 TRAIN.BATCH_SIZE 8`, I successfully run `run_net.py`. 

I get `checkpoint_epoch_00015.pyth`, and `cfg.SOLVER.MAX_EPOCH` is setting 15.

However, I get some ERRORs while running `test_net`.

The logs are as follows: [test_log.txt](https://github.com/facebookresearch/TimeSformer/files/6799907/test_log.txt)

I don't know how to deal with it. The three datasets are processed in the same way.

I am looking forward to hearing from you.

**Comment by gberta** [comment]
Some of your videos are either missing or they are corrupted. Please either re-download them, or remove them from your test.csv list.

**Comment by wsh-nie** [comment]
Thanks a lot!
