### ISSUE TITLE
Diving-48 dataset config file

### ISSUE THREAD

**Issue by eladb3** [facebookresearch/TimeSformer#62]
Hi,
thanks for providing this wonderful model.
Are you planning to add config file for the Diving-48 dataset?

Thanks, Elad.

**Comment by gberta** [comment]
Unfortunately, I can't make any modifications to the codebase as I'm no longer affiliated with FB. However, the Diving-48 configuration is essentially the same as Kinetics configurations. You would just need to update the paths to where your videos are stored, and also the number of classes. All the other hyperparameters were the same as for Kinetics.

**Comment by eladb3** [comment]
Thanks!
