### ISSUE TITLE
Can someone share the something-something v2?

### ISSUE THREAD

**Issue by kami93** [facebookresearch/TimeSformer#64]
Hi. As some people here might have already noticed, the something-something v2 dataset is not available online anymore, for unknown reasons. Since the dataset is widely used among video-understanding works, including TimeSformer, it would be useful for people to have an unofficial source for the dataset for reproducibility.

Can someone please share the dataset? Or make it available in, for example, https://academictorrents.com/ ?

**Comment by CastleLiang** [comment]
Same problem. Can someone help? Thanks!

**Comment by kami93** [comment]
The dataset is no more available.
