### ISSUE TITLE
Initialization of time_embed in VisionTransformer

### ISSUE THREAD

**Issue by kenshohara** [facebookresearch/TimeSformer#66]
I read timesformer.models.vit.py to confirm the implementation of VisionTransformer. In the implementation, pos_embed and cls_token is initialized by trunc_normal_ here.
https://github.com/facebookresearch/TimeSformer/blob/main/timesformer/models/vit.py#L214-L215
But time_embed is not initialized. Is this a just bug, or on purpose?

**Comment by gberta** [comment]
It's initialized to all zero values so that the model would learn to incorporate temporal information gradually. Our initialization ensures that at the very first iteration, the TimeSformer model matches exactly the spatial Vision Transformer model. Hope this makes sense.

**Comment by kenshohara** [comment]
Thank you for answering. I understood why you initialize time_embed by zero values.
