### ISSUE TITLE
About the intuition of “temporal fc”

### ISSUE THREAD

**Issue by jianghaojun** [facebookresearch/TimeSformer#7]
In your implementation, there is an unusual [self.temporal_fc (nn.Linear)](https://github.com/facebookresearch/TimeSformer/blob/2a181ec59c58066ffad20bd3ee876e6ca3bf90b4/lib/models/vit.py#L106) layer when using 'divided_space_time' attention.

Model definition:
``` 
if self.attention_type == 'divided_space_time':
    self.temporal_norm1 = norm_layer(dim)
    self.temporal_attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)
    self.temporal_fc = nn.Linear(dim, dim)
```

Model forward function:
```
elif self.attention_type == 'divided_space_time':
    ## Temporal
    xt = x[:, 1:, :]
    xt = rearrange(xt, 'b (h w t) m -> (b h w) t m', b=B, h=H, w=W, t=T)
    res_temporal = self.drop_path(self.temporal_attn(self.temporal_norm1(xt)))
    res_temporal = rearrange(res_temporal, '(b h w) t m -> b (h w t) m', b=B, h=H, w=W, t=T)
    res_temporal = self.temporal_fc(res_temporal)
    xt = x[:, 1:, :] + res_temporal
```

Before this self.temporal_fc (nn.Linear) layer, there is an attention layer which ends with a proj layer (nn.Linear). From a theoretical perspective, stacking two linear layer is still a linear layer which might not contribute a lot to the model capacity. 

Besides, I did an ablation experiments about this fc layer and found that it did contribute a lot to the performance which contradicts my intuition. Thus, could you explain the intuition for adding this temporal_fc layer?

**Comment by gberta** [comment]
The temporal_fc layer is not designed to increase the capacity of the model. It's meant to ensure that the temporal features are learned gradually without destroying the spatial features that the model is initialized with. 

Specifically, the temporal_fc layer is first initialized with zero weights, so during the first training iterations, the model only utilizes spatial information. As the training progresses, the model then learns to gradually incorporate temporal information. Our experiments suggest that this is an effective way to train TimeSformer.
