### ISSUE TITLE
Spatial and temporal attention calculation

### ISSUE THREAD

**Issue by y8han** [facebookresearch/TimeSformer#76]
Hi, I am now trying to visualize the spatial attention on each video images. I am following the attention rollout methods to draw the spatial attention. However, the results are really weird (the model "attends" to some bars).
I want to know if we only consider the spacial attention, do we need to take the temporal attentions into consideration?
I really appreciate any help! Thanks in advance.

**Comment by y8han** [comment]
Solved. I made a stupid error.

**Comment by petercmh01** [comment]
Hi: I also got many horizontal bars when I tried to visualized the attention. May I asked how you solved this ? I'm really appreciate any help! Thanks!

**Comment by y8han** [comment]
Hi, Its been quite a while.... I did not touch the codes since last year. But I believe there should be some stupid and obvious coding errors. For example, it may be the case that the index number of each spatial patches is inverse or the temporal index is inverse.
