### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by 87nohigher** [facebookresearch/TimeSformer#77]
I followed the the installation step
pip install timm 
and then it still show no module named 'timm'
it can only find timm with the command 
'conda install -c conda-forge timm'
but it would force me to download pytorch cpu,
which would result in torch.cuda.is_available() return false.
Any suggestion?

**Comment by gberta** [comment]
I just tested 'pip install timm', and it's working fine for me. Therefore, I would double check your environment/configuration.

**Comment by 87nohigher** [comment]
> I just tested 'pip install timm', and it's working fine for me. Therefore, I would double check your environment/configuration.

it looks like I typed 'source activate timesformer' in anaconda base environment,
so 'which python' points to /home/username/anaconda3/envs/timesformer/bin/python.
However, 'which pip' points to /home/username/.local/bin/pip.
Solved by conda deactivate.
Thanks for your reply.
