### ISSUE TITLE
K600 labels?

### ISSUE THREAD

**Issue by cnut1648** [facebookresearch/TimeSformer#87]
Hi, I would like to reproduce your work on k600. I have followed the instruction in the `DATASET.md`, and download the k600 [from here](https://github.com/cvdfoundation/kinetics-dataset). However I noticed that there is no label for the K600 test set (I also made [an issue there](https://github.com/cvdfoundation/kinetics-dataset/issues/22#issue-1092921467https://github.com/cvdfoundation/kinetics-dataset/issues/22#issue-1092921467)).

I'm wondering could you also share with us the label you were testing on? Thank you!

**Comment by gberta** [comment]
I believe that the results were reported on the validation set (if my memory serves me right).

**Comment by cnut1648** [comment]
Hi @gberta, yeah I assume this is so. I can reproduce the result on the val set using the ckpt provided in the repo. Thanks!
