### ISSUE TITLE
Fine-tuning TimeSformer on a smaller dataset

### ISSUE THREAD

**Issue by mtv21** [facebookresearch/TimeSformer#88]
Hi @gberta , I'd like to fine-tune 'TimeSformer_divST_8x32_224_K400' on a smaller [dataset](https://www.robots.ox.ac.uk/~alonso/tv_human_interactions.html).
How should I prepare the dataset ? Because in DATASET.md I only read about the ssv2 or Kinect possibilities.
Thanks a lot.

**Comment by happyBroJk** [comment]
Hi@mtv21 ,can you tell me how you test the  model ? What is your command?

**Comment by gberta** [comment]
Try to format your new dataset in a similar style as Kinetics or SSv2. Then you would be able to train the model on the new dataset, with minimal code modifications. You'll just need to provide different video/label lists in your configuration files.

**Comment by mtv21** [comment]
Thanks, it works!
